//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNIP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_UNIPPIMEntities4 : DbContext
    {
        public DB_UNIPPIMEntities4()
            : base("name=DB_UNIPPIMEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DT_Endereco> DT_Endereco { get; set; }
        public virtual DbSet<DT_Pessoa> DT_Pessoa { get; set; }
        public virtual DbSet<DT_Telefone> DT_Telefone { get; set; }
        public virtual DbSet<DT_Telefone_Tipo> DT_Telefone_Tipo { get; set; }
    }
}
